spring.application.name=Elite Buy Online Shopping Website

server.port = 4040


spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/elite_buy
spring.datasource.username=root
spring.datasource.password=my-Sql24;
#spring.datasource.password=netweb12
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql: true

razorpay.api.key = rzp_test_eia2GgXVbWLEN0
razorpay.api.secret = l2OKecP2Hm9oEm6UgOhLzmoy

spring.mail.host = smtp.gmail.com
spring.mail.port = 587
spring.mail.username =elitebuy.shopping@gmail.com
spring.mail.password =mgvaajducnxkdcwp
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true
